import {NextResponse} from 'next/server';
import crypto from 'node:crypto';
import {readDB,writeDB,userFromRequest,logActivity} from '../../../lib/server';
import {products} from '../../../products';
import {addSystemMessage} from '../../../lib/notifications';
export const runtime='nodejs';
export async function GET(req:Request){const admin=userFromRequest(req);if(!admin||admin.role!=='admin')return NextResponse.json({error:'Forbidden'},{status:403});const db=readDB();return NextResponse.json({orders:db.orders||[],users:db.users.map((u:any)=>({id:u.id,name:u.name,email:u.email,balance:Number(u.balance||0),profit:Number(u.profit||0),status:u.status,role:u.role}))},{headers:{'Cache-Control':'no-store'}})}
export async function POST(req:Request){const admin=userFromRequest(req);if(!admin||admin.role!=='admin')return NextResponse.json({error:'Forbidden'},{status:403});const body=await req.json();const customerId=String(body.customerId||'');const productId=Number(body.productId);const commissionPercent=Number(body.commissionPercent);const customer=readDB().users.find((u:any)=>u.id===customerId&&u.role==='customer');const product=products.find(p=>p.id===productId);if(!customer||!product)return NextResponse.json({error:'Customer or product not found'},{status:404});if(!Number.isFinite(commissionPercent)||commissionPercent<10||commissionPercent>15)return NextResponse.json({error:'Commission must be between 10% and 15%'},{status:400});const db=readDB();const orderAmount=product.price;const commission=Math.round(orderAmount*commissionPercent)/100;const order={id:crypto.randomUUID(),customerId,productId,productName:product.name,image:product.image,orderAmount,commission,commissionPercent,totalAmount:orderAmount+commission,status:'sent',createdAt:new Date().toISOString()};db.orders=db.orders||[];db.orders.unshift(order);logActivity(db,admin.id,'ORDER_SENT',`Sent ${product.name} to ${customer.name}`);
addSystemMessage(db,customer.id,`A new order is available: ${product.name}. Order Amount: $${orderAmount.toFixed(2)}. Commission: $${commission.toFixed(2)} (${commissionPercent}%).`);writeDB(db);return NextResponse.json({order})}
