import {NextResponse} from 'next/server';
import crypto from 'node:crypto';
import {readDB,writeDB,userFromRequest,logActivity} from '../../lib/server';
export const runtime='nodejs';
function auth(req:Request){return userFromRequest(req)}
function getOrCreate(db:any,customerId:string){let c=db.conversations.find((x:any)=>x.customerId===customerId);if(!c){c={id:crypto.randomUUID(),customerId,status:'open',updatedAt:new Date().toISOString()};db.conversations.push(c)}return c}
function serialize(db:any,c:any,userId?:string){const customer=db.users.find((u:any)=>u.id===c.customerId);const messages=db.messages.filter((m:any)=>m.conversationId===c.id);const unreadCount=userId?messages.filter((m:any)=>m.senderId!==userId&&!(m.senderId==='system'&&db.users.find((u:any)=>u.id===userId)?.role==='admin')&&!((m.readBy||[]).includes(userId))).length:0;return {...c,customer:customer?{id:customer.id,name:customer.name,email:customer.email}:null,messages,unreadCount}}
function allUnread(db:any,userId:string){const u=db.users.find((x:any)=>x.id===userId);return db.messages.filter((m:any)=>m.senderId!==userId&&!(m.senderId==='system'&&u?.role==='admin')&&!((m.readBy||[]).includes(userId))).length}
export async function GET(req:Request){const user=auth(req);if(!user)return NextResponse.json({error:'Not authenticated'},{status:401});const db=readDB();if(user.role==='admin'){const sorted=[...db.conversations].sort((a:any,b:any)=>new Date(b.updatedAt||0).getTime()-new Date(a.updatedAt||0).getTime());return NextResponse.json({conversations:sorted.map((c:any)=>serialize(db,c,user.id)),unreadCount:allUnread(db,user.id)},{headers:{'Cache-Control':'no-store'}})}const c=db.conversations.find((x:any)=>x.customerId===user.id);return NextResponse.json({conversation:c?serialize(db,c,user.id):null,unreadCount:allUnread(db,user.id)},{headers:{'Cache-Control':'no-store'}})}
export async function POST(req:Request){const user=auth(req);if(!user)return NextResponse.json({error:'Not authenticated'},{status:401});const body=await req.json();
 if(body.action==='startConversation'){if(user.role!=='customer')return NextResponse.json({error:'Only customers can start a conversation'},{status:403});const db=readDB();const c=getOrCreate(db,user.id);writeDB(db);return NextResponse.json({conversation:serialize(db,c,user.id),unreadCount:allUnread(db,user.id)});}
 if(body.action==='markRead'){const db=readDB();const customerId=user.role==='admin'?String(body.customerId||''):user.id;const c=db.conversations.find((x:any)=>x.customerId===customerId);if(c){for(const m of db.messages.filter((x:any)=>x.conversationId===c.id&&x.senderId!==user.id)){m.readBy=Array.isArray(m.readBy)?m.readBy:[];if(!m.readBy.includes(user.id))m.readBy.push(user.id)}}writeDB(db);return NextResponse.json({ok:true,unreadCount:allUnread(db,user.id)})}
 const text=String(body.text||'').trim();const imageUrl=typeof body.imageUrl==='string'&&body.imageUrl.startsWith('data:image/')?body.imageUrl:'';if(!text&&!imageUrl)return NextResponse.json({error:'Message or image is required'},{status:400});const db=readDB();let customerId=user.id;if(user.role==='admin'){customerId=String(body.customerId||'');if(!db.users.some((u:any)=>u.id===customerId&&u.role==='customer'))return NextResponse.json({error:'Customer not found'},{status:404})}const c=getOrCreate(db,customerId);const message={id:crypto.randomUUID(),conversationId:c.id,senderId:user.id,text,imageUrl:imageUrl||undefined,createdAt:new Date().toISOString(),readBy:[]};db.messages.push(message);c.updatedAt=message.createdAt;c.status='open';logActivity(db,user.id,'SUPPORT_MESSAGE_SENT',`${user.role} sent a support message`);writeDB(db);return NextResponse.json({message,conversation:serialize(db,c,user.id)})}
