"use client";
import Link from "next/link"; import {UserShell} from "../components"; import {apiFetch,apiMe} from "../lib"; import {useEffect,useState} from "react";
export default function Dashboard(){
 const[data,setData]=useState<any>(null); const[orders,setOrders]=useState<any[]>([]);
 useEffect(()=>{let dead=false;const load=async()=>{const [me,ro]=await Promise.all([apiMe(),apiFetch("/api/orders",{cache:"no-store"})]);const d=await ro.json();if(!dead){setData(me);setOrders(Array.isArray(d?.orders)?d.orders:[])}};load().catch(()=>{});const t=setInterval(()=>load().catch(()=>{}),1000);return()=>{dead=true;clearInterval(t)}},[]);
 const active=orders.filter(o=>["pending","handed_over","on_the_way","delivered"].includes(o.status)).length,completed=orders.filter(o=>o.status==="completed").length;
 return <UserShell><div className="info-banner live-banner"><b><i className="live-dot"/>Live account</b></div><div className="stat-grid dashboard-stats"><div className="stat balance-stat"><span>Total Balance</span><strong>${Number(data?.user?.balance||0).toFixed(2)}</strong><small>Your current balance</small></div><div className="stat profit-stat"><span>Total Profit</span><strong>${Number(data?.user?.profit||0).toFixed(2)}</strong><small>Your completed earnings</small></div><div className="stat"><span>Active Orders</span><strong>{active}</strong><small>In delivery flow</small></div><div className="stat"><span>Completed Orders</span><strong>{completed}</strong><small>All completed orders</small></div></div>
 <div className="content-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Shopping overview</span><h2>How it works</h2></div><Link className="btn btn-small btn-ghost" href="/products">Browse products</Link></div><div className="how-it-works"><div><b>1 · Browse</b><span>Explore the Top 100 Products and choose something you like.</span></div><div><b>2 · Review</b><span>Open a product to see its amount, commission range and delivery estimate.</span></div><div><b>3 · Order</b><span>Available orders appear in your Orders area when they are ready.</span></div><div><b>4 · Track</b><span>Follow your order status and see completed earnings in your account.</span></div></div></section><section className="panel profile-card"><span className="eyebrow">Customer support</span><div className="profile-avatar">?</div><h2>Need help?</h2><p>If your Total Balance is insufficient, contact customer support.</p><Link className="btn full" href="/support">Open customer service</Link></section></div></UserShell>
}
